# Generated by Django 3.2 on 2023-04-24 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
        migrations.RemoveField(
            model_name='books',
            name='bookmark',
        ),
        migrations.RemoveField(
            model_name='books',
            name='endpaper',
        ),
        migrations.AddField(
            model_name='books',
            name='coment',
            field=models.CharField(blank=True, choices=[('red', 'Red'), ('green', 'Green'), ('blue', 'Blue'), ('yellow', 'Yellow'), ('orange', 'Orange'), ('purple', 'Purple'), ('pink', 'Pink'), ('brown', 'Brown'), ('gray', 'Gray'), ('black', 'Black'), ('white', 'White')], default='', max_length=50, verbose_name='Коментар'),
        ),
    ]
