# Generated by Django 3.2 on 2023-04-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20230424_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='coment',
        ),
        migrations.AddField(
            model_name='books',
            name='bookmark',
            field=models.CharField(blank=True, default='#FFFFFF', max_length=20, verbose_name='Закладка'),
        ),
        migrations.AddField(
            model_name='books',
            name='endpaper',
            field=models.CharField(blank=True, default='#FFFFFF', max_length=20, verbose_name='Форзац'),
        ),
    ]
