# Generated by Django 3.2 on 2023-06-18 13:27

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20230430_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='bookmark',
            field=colorful.fields.RGBColorField(blank=True, null=True, verbose_name='Закладка'),
        ),
        migrations.AlterField(
            model_name='books',
            name='captal',
            field=colorful.fields.RGBColorField(blank=True, null=True, verbose_name='Каптал'),
        ),
    ]
